// /ai-training/ — the corporate AI training pillar (design canvas: Training / ZH-Training). Indexable, self-canonical.
import { SITE, EMAIL, SMS_TEL, SMS_DISPLAY, GBP_URL, TRAINING, PROOF } from '../config.mjs';
import { planBtn, photoHero, ctaBand, L } from '../layout.mjs';
import { breadcrumb } from '../components.mjs';
import { caseProof } from './cases.mjs';
import { business, person, faqPage } from '../schema.mjs';

const SMS = `sms:${SMS_TEL}?body=TRAINING%20-%20`;
const PRICE = `$${TRAINING.halfDayFrom.toLocaleString()}`, MAX = TRAINING.halfDayMax;

const C = {
  en: {
    title: 'Corporate AI Training for Teams | AI Man Jack',
    description: `Hands-on corporate AI training for teams in Dallas and remotely, in English or Chinese. Each person leaves with one working AI workflow for a task they already do. Half-day from ${PRICE}.`,
    og: { title: 'Corporate AI Training Built Around Real Work', description: `Each person brings one task they already do and leaves with a working AI workflow for it. Dallas onsite or remote, in English or Chinese. ${PROOF.rating} on Google across ${PROOF.reviews} reviews.`, alt: 'Hands-on corporate AI training for your team, in English or Chinese' },
    crumb: 'AI training', eyebrow: 'Corporate AI training · Dallas onsite or remote · English or Chinese', h1: 'Corporate AI training built around <em>real work</em>',
    sub: 'Each person brings one task they already do every week and leaves with a working AI workflow for it, plus the habit of checking the output before it goes out.',
    text: 'Prefer to text? Send TRAINING to', heroAlt: 'A full classroom in Dallas at one of Jack Qian’s hands-on AI workshops',
    stats: [[PRICE, `Half-day workshop, up to ${MAX} people, at your office`], ['24 hrs', 'Written quote after one 30-minute call, no add-ons'], ['EN · 中文', 'Taught in whichever language the room works in'], [`${PROOF.rating} ★`, `${PROOF.reviews} Google reviews, all from workshop attendees`]],
    teamsK: 'Who it’s for', teamsH: 'Teams that don’t write code and do repeat work', teamsP: 'Every team works on tasks it already does. These are the workflows each one builds in a session.',
    teams: [['sales', 'Sales', ['Account research before a first call, from the prospect’s site and your CRM notes', 'Meeting prep: five points to raise, drafted from last call’s notes', 'Follow-up emails drafted from call notes, in your voice', 'First-draft proposals from an approved template']], ['operations', 'Operations', ['The same weekly report, built from the same spreadsheet, every week', 'Process documentation from a recorded walkthrough', 'Meeting notes turned into action items with owners', 'Fields pulled out of invoices, forms and PDFs into a table']], ['marketing', 'Marketing', ['Research synthesis from a stack of articles into one brief', 'Campaign briefs from a filled-in template', 'One piece of content repurposed into three formats', 'Performance summaries from exported numbers']], ['leaders', 'Leaders & managers', ['Which tasks are worth AI, scored on four questions', 'Where a human must sign off before an output is used', 'What data may go into a tool and what may not', 'A two-week check: keep, change or stop each workflow']]],
    curK: 'What we cover', curH: 'Task first, tool second.', curP: 'Non-technical teams arrive overwhelmed by AI products, or with an impressive chatbot answer that doesn’t fit their job. A product tour makes both worse. So every session works through one real task in five parts.', curNote: 'Two weeks later: was it tested, was it accurate enough to use, should it continue, change or stop?',
    cur: [['Choose a suitable task', 'Each person lists three things they repeat every week and scores them: often enough to matter, clear input and output, quick to check, testable without sensitive information.', '“Prepare a five-point meeting brief from these approved notes” is teachable. “Run my department” is not.'], ['Give the AI useful context', 'A prompt is a work instruction, not a secret formula: a goal, an approved source, constraints, a usable format, and what to flag for a person to verify.'], ['Move from chat to workflow', 'A chat produces an answer. A workflow moves information through steps: collect approved notes, extract decisions, identify owners, draft follow-ups, put the result in a review queue.', 'This is where a team learns the difference between a chatbot and an agent.'], ['Verify the output', 'Can every claim be traced to the source? What context is missing? Who approves it before use? At least one output in every session is deliberately flawed — finding it teaches more than another perfect demo.'], ['Apply data and approval guardrails', 'Every participant leaves with a clear answer to three questions: which tools are approved, which information is off-limits, and where a human must sign off.']],
    fmtK: 'Formats', fmtH: 'Three ways to run it', fmtP: 'All three follow the same five parts. What changes is how much each person does with their own hands.', quote: 'Get a quote for this format',
    fmt: [['session', '90 min', 'One task · one live build · one checklist', '', ['A live build on a task taken from your team, not a canned demo', 'The five-part instruction template, reusable the same afternoon', 'A one-page verification checklist'], 'Good for a first look across a whole department.'], ['hands-on workshop', 'Half day', 'Everyone builds · bring laptops and one real task each', `From ${PRICE} · up to ${MAX} people`, ['Each person leaves with a working workflow for a task they already do', 'A deliberately flawed output to catch', 'A pilot plan with an owner, a tool and a first test date'], 'This is the format the Google reviews are about.'], ['AI workflow program', 'Multi-week', 'For a team that wants the workflows to stick', '', ['Weekly sessions on the team’s own tasks, one workflow at a time', 'Review of what actually ran between sessions, and what broke', 'A written playbook the team keeps'], 'Scoped after the half-day, once we know which tasks are worth it.']],
    revK: 'Reviewed on Google', revH: 'What attendees say', revP: `${PROOF.rating} across ${PROOF.reviews} Google reviews, all from people who came to a community AI workshop in Dallas.`, revMore: `Read all ${PROOF.reviews} on Google →`, revBy: 'Google review · Dallas AI workshop',
    rev: [['emily xu', '“I had such a great experience at this AI workshop. It was practical, inspiring, and genuinely fun. Jack, the host, did an amazing job of breaking down complex AI concepts in a way that was easy to understand…”'], ['U Rachel', '“I really enjoyed Jack’s AI seminar! He has a very forward-thinking perspective on AI and does a great job of explaining everything from understanding AI to actually using it in real life…”'], ['Yuqi Guan', '“This AI course was very informative and easy to follow. It covered the fundamentals of AI and its basic applications, making it especially suitable for beginners with little or no prior experience.”']],
    fromK: 'Where the method came from', fromH: 'Five talks, one hackathon, and a lot of rewriting.', fromP: 'The task-scoring exercise, the deliberately flawed output, the two-week check-in — each one earned its place by working in front of fifty people, or got cut. The five parts above are the ones that survived.', fromAlt: 'Jack Qian teaching a hands-on community AI workshop in Dallas',
    faqK: 'Common questions', faqH: 'The training, answered plainly',
    faq: [['Who is the AI training for?', 'Teams of roughly 5 to 60 people where most people are not technical: sales, operations, marketing, admin, front office, planning, customer service, and the managers who lead them. No coding. Everyone works on a task they already do.'], ['What do people actually build during the training?', 'One working workflow for a task they already do every week — a meeting brief from approved notes, a first-draft customer reply, a weekly report pulled from a spreadsheet, a research summary on an account. It runs by the end of the session, and each person leaves with a checklist for verifying the output before it goes out.'], ['Is the training in English or Chinese?', 'Either. The community series in Dallas in 2026 ran in Chinese; company sessions run in whichever language the room works in, and the materials come in both.'], ['Which AI tools does the training use?', 'Whatever your company has already approved — ChatGPT, Claude, Gemini, Copilot. The method is the same across tools. The first thing covered is which data may go into a tool and which may not.'], ['How much does AI training for a team cost?', `Half-day workshops start at ${PRICE} for teams of up to ${MAX}, at your office. 90-minute sessions and multi-week programs are quoted by team size. <a href="/book/">Book a 30-minute call</a>; you’ll have a recommended format and a written quote within 24 hours, with no add-ons.`], ['How do you know whether the training worked?', 'Two weeks after the session, we check whether the workflow was tested on real work, whether the result was accurate enough to use, where review took too long, and whether the task should continue, change, or stop. Attendance and satisfaction scores are not the measure.'], ['Can the training be run at our office? What about remote?', 'Yes to both. Sessions are in person anywhere in the Dallas–Fort Worth metroplex — Dallas, Fort Worth, Plano, Richardson, Frisco, McKinney, Arlington, and everywhere between. Remote sessions run over video for teams outside DFW or spread across offices.']],
    bioK: 'Who teaches it', bio: '“I run community AI workshops here in Dallas because useful AI education should be accessible, and I teach companies the same way. Every session starts with one real task and an honest answer about whether AI belongs there.”', bioBy: 'founder, AI Man Jack', bioMore: 'More about Jack →',
  },
  zh: {
    title: '面向团队的企业 AI 培训 | AI Man Jack',
    description: `面向达拉斯及远程团队的实操型企业 AI 培训，中英文授课。每位学员带走一条针对自身任务的可用 AI 工作流。半天工作坊 ${PRICE} 起。`,
    og: { title: '围绕真实工作设计的企业 AI 培训', description: `每位学员带来一项每周都在做的任务，带走一条可用的 AI 工作流。达拉斯上门或远程，中英文授课。Google ${PROOF.reviews} 条评价，${PROOF.rating} 分。`, alt: '面向团队的实操型企业 AI 培训，中英文授课' },
    crumb: 'AI 培训', eyebrow: '企业 AI 培训 · 达拉斯现场或远程 · 中英文授课', h1: '围绕<em>真实工作</em>设计的<br>企业 AI 培训',
    sub: '每位学员带来一项每周都在做的任务，课程结束时带走一条可用的 AI 工作流，并养成输出前先核验的习惯。',
    text: '更习惯短信？发送 TRAINING 至', heroAlt: '达拉斯，Jack Qian 主讲的一场 AI 实操工作坊，教室座无虚席',
    stats: [[PRICE, `半天工作坊，最多 ${MAX} 人，上门授课`], ['24 小时', '一次 30 分钟沟通后提供书面报价，无附加费用'], ['EN · 中文', '根据团队习惯选择授课语言'], [`${PROOF.rating} ★`, `${PROOF.reviews} 条 Google 评价，均来自工作坊学员`]],
    teamsK: '适用团队', teamsH: '适合不写代码、但有大量重复性工作的团队', teamsP: '每个团队都基于自己已有的工作任务练习。以下是各团队在课程中实际搭建过的工作流。',
    teams: [['sales', '销售', ['首次通话前的客户调研：基于对方官网与 CRM 记录', '会前准备：根据上次通话记录整理五个要点', '根据通话记录起草跟进邮件，保持个人风格', '基于已审批模板生成方案初稿']], ['operations', '运营', ['基于同一份表格，每周生成固定格式的周报', '根据操作录屏整理流程文档', '将会议纪要转化为明确负责人的待办事项', '从发票、表单和 PDF 中提取字段并整理成表格']], ['marketing', '市场', ['将大量文章综合为一份研究简报', '根据模板生成投放简报', '将一篇内容改编为三种形式', '根据导出的数据撰写效果总结']], ['leaders', '管理者', ['用四个问题评估哪些任务值得引入 AI', '明确哪些输出在使用前必须由人审批', '规定哪些数据可以输入工具、哪些不可以', '两周复盘：每条工作流是保留、调整还是停止']]],
    curK: '课程内容', curH: '先定任务，再选工具。', curP: '非技术团队通常面临两种困境：要么被层出不穷的 AI 产品弄得无所适从，要么试过聊天机器人、得到了令人印象深刻的回答，却不知道如何融入自己的工作。产品演示只会让问题更严重。因此，每一次课程都围绕一项真实任务，分五个部分展开。', curNote: '两周后回访：是否经过实测？结果是否足够准确？应继续、调整还是停止？',
    cur: [['选择合适的任务', '每位学员列出三项每周重复的工作，并按四个标准打分：频率是否足够高、输入输出能否清晰描述、能否快速核验、能否在不涉及敏感信息的情况下测试。', '“根据这份已批准的会议记录整理五点会议简报”可以教；“帮我管理整个部门”则不行。'], ['为 AI 提供有效上下文', '提示词是一份工作指令，而不是什么秘诀：明确目标、指定可信来源、设定约束、规定输出格式，并标出需要人工核验的内容。'], ['从对话升级为工作流', '对话产出的是一个回答；工作流则让信息按步骤流转：收集已批准的记录、提取决策、明确负责人、起草跟进、进入审核队列。', '团队会在这一步理解聊天机器人与智能体（Agent）的区别。'], ['核验输出结果', '每条结论能否追溯到来源？缺少哪些上下文？使用前由谁审批？每场课程至少有一个刻意设置的错误输出——找出它，比再看一次完美演示更有价值。'], ['落实数据与审批规范', '每位学员都能明确回答三个问题：哪些工具已获批准、哪些信息不得输入、哪些环节必须由人签字确认。']],
    fmtK: '培训形式', fmtH: '三种授课方式', fmtP: '三种形式都遵循同样的五个部分，区别在于每位学员亲自动手的程度。', quote: '获取该形式报价',
    fmt: [['专题分享', '90 分钟', '一项任务 · 一次现场搭建 · 一份核验清单', '', ['基于团队真实任务的现场演示，而非预设案例', '当天即可复用的五要素指令模板', '一页纸的输出核验清单'], '适合整个部门初步了解。'], ['实操工作坊', '半天', '人人动手 · 请携带电脑和一项真实任务', `${PRICE} 起 · 最多 ${MAX} 人`, ['每位学员带走一条针对自身任务的可用工作流', '找出刻意设置的错误输出，养成核验习惯', '一份包含负责人、工具和首次测试日期的试点计划'], 'Google 评价所涉及的正是这一形式。'], ['AI 工作流项目', '多周', '适合希望工作流长期落地的团队', '', ['每周基于团队自身任务落地一条工作流', '复盘课间实际运行的情况与问题', '一份团队可长期保留的书面操作手册'], '在半天工作坊之后，根据值得投入的任务确定范围。']],
    revK: 'Google 评价', revH: '学员反馈', revP: `Google 上共 ${PROOF.reviews} 条评价，均为 ${PROOF.rating} 分，全部来自参加过达拉斯社区 AI 工作坊的学员。`, revMore: `查看全部 ${PROOF.reviews} 条评价 →`, revBy: 'Google 评价 · 达拉斯 AI 工作坊 （译自英文原评）',
    rev: [['emily xu', '“这次 AI 工作坊的体验非常好：实用、有启发，而且真的很有趣。Jack 把复杂的 AI 概念讲解得通俗易懂……”'], ['U Rachel', '“非常喜欢 Jack 的 AI 讲座！他对 AI 有很前瞻的视角，从理解 AI 到在实际生活中使用，都讲得非常清楚……”'], ['Yuqi Guan', '“这门 AI 课程信息量大、容易跟上，涵盖了 AI 的基础知识和基本应用，尤其适合几乎没有相关经验的初学者。”']],
    fromK: '方法的由来', fromH: '五场讲座、一场黑客松，以及反复打磨。', fromP: '任务评分练习、刻意设置的错误输出、两周回访——每一个环节都在五十人的课堂上经过检验，有效的保留，无效的删除。上面的五个部分，正是经过检验留下来的。', fromAlt: 'Jack Qian 在达拉斯主讲一场社区 AI 实操工作坊',
    faqK: '常见问题', faqH: '关于培训，直接回答',
    faq: [['培训适合哪些人？', '5 到 60 人左右、以非技术背景为主的团队：销售、运营、市场、行政、前台、计划、客服，以及带领这些团队的管理者。无需编程，每个人都基于自己已有的任务练习。'], ['学员在培训中实际会搭建什么？', '一条针对自己每周固定任务的可用工作流：例如根据已批准的记录整理会议简报、起草客户回复、从表格生成周报，或撰写某个客户的调研摘要。课程结束前即可运行，每位学员还会带走一份核验清单，用于在输出发出前逐项检查。'], ['培训使用中文还是英文？', '均可。2026 年在达拉斯举办的社区系列讲座以中文进行；企业课程则采用团队最习惯的语言，课程资料提供中英文两个版本。'], ['培训使用哪些 AI 工具？', '使用贵公司已批准的工具，例如 ChatGPT、Claude、Gemini 或 Copilot。方法适用于各类工具。课程首先明确的，是哪些数据可以输入工具、哪些不可以。'], ['团队 AI 培训的费用是多少？', `半天工作坊 ${PRICE} 起，最多 ${MAX} 人，可上门授课。90 分钟专题分享与多周项目按团队规模报价。<a href="/zh/book/">预约 30 分钟通话</a>，24 小时内即可收到推荐方案与书面报价，无任何附加费用。`], ['如何判断培训是否有效？', '课程结束两周后，我们会确认：工作流是否在真实工作中经过测试、结果是否足够准确、哪个核验环节耗时过长，以及该任务应继续、调整还是停止。出勤率与满意度评分不作为衡量标准。'], ['可以到我们办公室授课吗？远程可以吗？', '两种方式均可。我们可在达拉斯—沃斯堡都会区的任何地点上门授课，包括 Dallas、Fort Worth、Plano、Richardson、Frisco、McKinney、Arlington 及周边城市。位于该地区之外或分布在多个办公室的团队，可通过视频远程授课。']],
    bioK: '授课讲师', bio: '“我在达拉斯举办社区 AI 工作坊，因为实用的 AI 教育应当人人可及；为企业授课，我也秉持同样的方式。每一次课程都从一项真实任务开始，并坦诚回答：这件事是否真的适合交给 AI。”', bioBy: 'AI Man Jack 创始人', bioMore: '了解更多 →',
  },
};
export const TRAINING_FAQ = { en: C.en.faq, zh: C.zh.faq };

const page = (lang) => {
  const c = C[lang], bc = breadcrumb(lang, [[c.crumb, '/ai-training/']]);
  const head = (k, h, p, more) => `<div class="sec-head"><div><div class="eyebrow">${k}</div><h2>${h}</h2>${p ? `<p class="lead">${p}</p>` : ''}</div>${more || ''}</div>`;
  return {
    title: c.title, description: c.description, og: c.og, view: 'training_page_view', hero: 'photo',
    body: `${photoHero({ photo: 'workshop', alt: c.heroAlt, size: 'md', stats: c.stats, inner: `<div class="hero-main stack">${bc.html}<div class="eyebrow">${c.eyebrow}</div><h1 class="lg" style="font-size:clamp(44px,6.4vw,92px)">${c.h1}</h1><p style="max-width:720px">${c.sub}</p>
<div class="cta-row" style="gap:20px">${planBtn(lang, { pos: 'training-hero', id: 'hero-cta' })}<span style="font-size:15px;color:var(--on-photo)">${c.text} <a href="${SMS}" data-event="sms_training_click" data-pos="training-hero">${SMS_DISPLAY}</a></span></div></div>` })}

<section class="sec" id="teams"><div class="wrap">${head(c.teamsK, c.teamsH, c.teamsP)}
<div class="g4">${c.teams.map(([slug, name, items]) => `<div class="oak" id="team-${slug}" style="gap:18px;padding:30px 28px"><h3 style="font-size:26px">${name}</h3><ul class="ticks">${items.map((i) => `<li><span>${i}</span></li>`).join('')}</ul></div>`).join('')}</div></div></section>

<section class="sec dark" id="curriculum"><div class="wrap g12">
<div style="grid-column:span 4;display:flex;flex-direction:column;gap:20px"><div class="eyebrow">${c.curK}</div><h2 style="font-size:clamp(36px,4.4vw,64px);line-height:1">${c.curH}</h2><p style="font-size:17px;line-height:1.65">${c.curP}</p><p style="margin-top:12px;padding-top:20px;border-top:1px solid var(--dark-line);font-size:15.5px;line-height:1.65">${c.curNote}</p></div>
<ol class="nums" style="grid-column:6 / span 7">${c.cur.map(([h, p, why], i) => `<li><span class="n">${i + 1}</span><div><h3 style="font-size:26px">${h}</h3><p>${p}</p>${why ? `<span class="why">${why}</span>` : ''}</div></li>`).join('')}</ol></div></section>

${caseProof(lang)}
<section class="sec" id="formats"><div class="wrap">${head(c.fmtK, c.fmtH, c.fmtP)}
<div class="g3" style="align-items:stretch">${c.fmt.map(([k, big, sub, chip, items, note], i) => `<div class="prog${i === 1 ? ' dark on-dark' : ''}"><span class="k">${k}</span><span class="big">${big}</span><span class="sub">${sub}</span>${chip ? `<span class="chip">${chip}</span>` : ''}<ul class="ticks">${items.map((x) => `<li><span>${x}</span></li>`).join('')}</ul>${planBtn(lang, { pos: 'training-format', label: c.quote })}<span class="note">${note}</span></div>`).join('')}</div></div></section>

<section class="sec tight" id="testimonials"><div class="wrap">${head(c.revK, c.revH, c.revP, `<a class="more" href="${GBP_URL}" target="_blank" rel="noopener">${c.revMore}</a>`)}
<div class="quote-grid">${c.rev.map(([name, q]) => `<figure class="quote"><span class="stars" aria-label="5 stars">★★★★★</span><blockquote style="margin:0;flex-grow:1"><p>${q}</p></blockquote><figcaption><b>${name}</b> <span>· ${c.revBy}</span></figcaption></figure>`).join('')}</div></div></section>

<section class="split-photo" id="community-proof"><img src="/img/events/dallas-multi-agent-workshop.webp" width="1200" height="900" loading="lazy" decoding="async" alt="${c.fromAlt}">
<div><div class="eyebrow">${c.fromK}</div><h2>${c.fromH}</h2><p>${c.fromP}</p></div></section>

<section class="sec" id="faq"><div class="wrap g12"><div style="grid-column:span 4;display:flex;flex-direction:column;gap:16px"><div class="eyebrow">${c.faqK}</div><h2 style="font-size:clamp(32px,3.6vw,52px)">${c.faqH}</h2></div>
<div class="faq" style="grid-column:6 / span 7">${c.faq.map(([q, a], i) => `<details${i === 0 ? ' open' : ''}><summary>${q}</summary><div class="faq-a"><p>${a}</p></div></details>`).join('\n')}</div></div></section>

<section class="sec tight" id="about"><div class="wrap"><div class="big-card" style="flex-direction:row;align-items:center;gap:32px;flex-wrap:wrap"><img src="/img/jack-portrait-256.webp" width="256" height="256" loading="lazy" decoding="async" alt="Jack Qian" style="width:120px;height:120px;border-radius:50%;object-fit:cover;flex:none">
<div style="display:flex;flex-direction:column;gap:10px;flex:1 1 320px"><div class="eyebrow">${c.bioK}</div><p style="font-size:clamp(17px,1.4vw,20px);line-height:1.6">${c.bio}</p><span style="font-size:15px;color:var(--muted)"><strong style="color:var(--ink)">Jack Qian</strong> · ${c.bioBy}</span></div><a class="more" href="${L(lang, '/about/')}">${c.bioMore}</a></div></div></section>
${ctaBand(lang, { pos: 'training-final' })}`,
    jsonld: [business(lang, { full: true }), person(), faqPage(c.faq, `${SITE}${L(lang, '/ai-training/')}#faq`), bc.ld],
  };
};

export const pages = [{ path: '/ai-training/', priority: 0.9, changefreq: 'weekly', en: page('en'), zh: page('zh') }];
