// Current (indexable) case studies. Source of truth for every fact below: Jack's build notes, 2026-09-19.
// Rules for editing: the ~6-hour figure is scoped to FIRST-DRAFT construction only and always sits next to the human-review
// caveat. Never write "6 hours saved", ROI, revenue or a net-time figure until review time has been measured.
// Client name, staff names, links and keys never appear here.
export const LIVESTREAM = {
  slug: 'livestream-agency-scheduling', date: '2026-09-19',
  en: {
    name: 'Weekly scheduling for a livestream agency',
    title: 'Case Study: Weekly Scheduling for a Livestream Agency | AI Man Jack',
    description: 'A TikTok Shop livestream agency built its weekly host and operator schedule by hand. Now the first draft is generated from rules the client keeps in its own spreadsheet.',
    card: 'The first draft used to take about six hours each week. Now it is generated from staff availability and client-owned rules; a person still reviews, edits and publishes it.',
    tags: ['Operations', 'Deterministic solver', 'Human review'],
    eyebrow: 'Case study · Operations',
    h1: 'A livestream agency that stopped building its weekly schedule from a blank sheet.',
    sub: 'The first draft used to take about six hours each week. Now it is generated automatically from staff availability, room requirements and rules the client controls in its own spreadsheet. A person still reviews, edits and publishes the final schedule.',
    trust: 'In production since September 2026 · Client name withheld · Human review remains',
    summaryH: 'In short',
    summary: [
      'A US TikTok Shop livestream agency schedules about 30 part-time hosts and operators across 8 brand rooms, roughly 10am–9pm, seven days a week.',
      'The first-draft scheduling work used to take about six hours each week. That first draft is now generated automatically; a person still reviews, edits and publishes the schedule.',
      'The scheduling engine is deterministic code, not a language model. The rules live in the client’s own spreadsheet.',
      'Changing the unit of work from hours to shows took mid-show operator changes from 41% to 0%. The last measured iteration staffed 456 role-hours and left 10 required shows unfilled, because of evening and weekend availability.',
      'Net hours saved are not claimed. Review time has not been measured yet.',
    ],
    factsH: 'Key facts',
    kv: [
      ['Business', 'TikTok Shop livestream agency, United States (name withheld)'],
      ['Business type', 'Runs brand livestream rooms with part-time hosts and operators'],
      ['Team being scheduled', 'About 30 part-time hosts and operators across 8 brand rooms, roughly 10am–9pm, seven days a week'],
      ['What the client asked for', 'Only the zero-to-one step: a usable first draft of next week’s schedule'],
      ['Outside the system', 'Attendance, payroll, daily briefings and final publishing stayed as they were'],
      ['Status', 'Live. A draft builds weekly; the operations lead reviews, edits and publishes'],
    ],
    beforeH: 'Before and now',
    beforeP: 'One operations lead collected next week’s availability by messaging each person, then filled the schedule cell by cell in a spreadsheet. Conflicts such as “available until 4, scheduled until 5” were found by eye after the fact.',
    beforeK: 'Before', before: ['About six hours each week to build the first draft', 'Availability collected person by person', 'Schedule filled cell by cell', 'Conflicts caught by eye', 'Rules lived partly in the operations lead’s head'],
    nowK: 'Now', now: ['Staff submit availability through signed links', 'Client-owned rules live in Lark', 'A deterministic solver generates the first draft', 'The output explains unfilled constraints', 'The operations lead reviews, edits and publishes'],
    caveat: 'A roughly six-hour weekly first-draft scheduling task is now automated; a person still reviews, edits and publishes the schedule.',
    builtH: 'What was built',
    built: [
      'One Cloudflare Worker with scheduled triggers. Each person gets a signed link that is valid for one week and one name; they pick a start and end time per day. Submissions land in the client’s Lark Base.',
      'Every Thursday the Worker reads availability, the client’s scoring sheets and room requirements, and writes a draft workbook back into Lark: one tab per day, a summary, and a plain-language page describing the logic.',
      '<strong>The rules belong to the client.</strong> Host-to-room scores, operator scores, who cannot work together, weekly hour ranges, and which rooms open when all live in the client’s spreadsheet. Changing a rule means editing a cell, not asking for a code change.',
      '<strong>What the system does not do:</strong> publish the schedule, message staff, track attendance, or decide on last-minute swaps.',
    ],
    llmH: 'Why deterministic code, not an LLM',
    llm: [
      'The scheduling solver is deterministic code, not a language model.',
      'Before this project the client had handed two months of past schedules to a chatbot and asked it to carry on the pattern. It did not learn the rules reliably. In the first meeting the operations lead said the model “learned it badly”; the owner’s brief was “if A then B, leave it no room.”',
      'The reason became clear later in the build. Historical schedules contain exceptions and residue that are not rules. Five percent of past shows were one hour long. That looked like a pattern; it was what was left when hosts called in sick. Anything that learns from that history copies the residue along with the rules.',
      'This workflow needed explicit constraints and predictable fallbacks. A negative pair score means never. A weekly cap means a cap. An empty slot has to say which constraint blocked it. A language model can still be useful around a workflow like this, for example turning a manager’s free-text note into a proposed rule that a person approves. The engine that makes the scheduling decision is deterministic.',
    ],
    lesson: 'Use an LLM where ambiguity is useful; use deterministic logic where business rules must be enforced exactly.',
    notesH: 'Implementation notes',
    notes: [
      'The first version assigned people hour by hour and produced schedules nobody could work: one person in five rooms in a day, operators swapped mid-show. Comparing against a real week showed why. People think in shows, the code was thinking in hours. The unit was changed to 2–3 hour shows with one host and one operator each.',
      'Operators are assigned before hosts. The client’s manager pointed out that the number of operators free at 2pm decides how many rooms can open at 2pm.',
      'A negative pair score means those two people are never put together, in any fallback. The client was explicit: anyone who could tolerably work together was not given a negative.',
      'When a show cannot be staffed the system first shortens it to two hours, then allows a lower-tier person, then lets someone cover a single remaining hour. If it still fails, the slot is left empty and the summary says which constraint blocked it and how many people it blocked.',
      'One host is an exception the client asked for: every hour that host is available is filled in one room, with no break and no caps. It is driven by a flag in the client’s sheet, not by a name in the code.',
      'Every day tab starts with a line stating its own weekday and date. The reason is in the failures section.',
      'After Wednesday the form closes to staff. The operations lead can still open anyone’s link, enter the admin key, and submit for them.',
      '32 automated tests run before every deploy. Ten of them reproduce bugs the client actually hit.',
    ],
    measureH: 'What was measured',
    measureP1: 'Structure of the generated week against a real hand-built week, before and after the unit changed from hours to shows:',
    t1: { head: ['', 'Hand-built week', 'Hour-by-hour version', 'Show-based version'],
      rows: [['One-hour shows', '5%', '17%', '3%'], ['Operator changed mid-show', '26%', '41%', '0%'], ['Most rooms one person worked in a day', '2', '5', '2'], ['Longest day for one person', '7h', '8h', '7h']] },
    measureP2: 'Coverage for one week as rules were added, with the number of required shows left unfilled. The unit is role-hours: one staffed room-hour counts as two role-hours, one host plus one operator.',
    t2: { head: ['Change', 'Role-hours', 'Unfilled'],
      rows: [['Show-based solver', '392', '25'], ['Match score as strict priority', '420', '20'], ['Operator first', '440', '18'], ['Lower-tier fill-in allowed', '446', '16'], ['One-hour cover allowed', '456', '10']] },
    measureP3: 'The ten that remained were evenings after 7pm and weekend shows. The summary showed why: more than twenty people’s submitted hours did not reach those slots. That is a staffing fact, not something ordering can fix.',
    failH: 'What broke before the workflow became reliable',
    fails: [
      ['Friday, Saturday and Sunday were written into the wrong tabs.', 'Adding a tab shifted every day one position. Nothing errored, and the shifted output looked plausible because Saturday and Sunday have the same shape. The client caught it: “lots of people can work Friday and none are scheduled.” Fixed with a hard check before writing, plus the self-labelling first row.'],
      ['Nobody could submit for most of a day.', 'A query meant to update a person’s existing row used a date filter Lark rejected. The client found it while submitting on someone’s behalf.'],
      ['A rule was inferred from history that was not a rule.', 'Five percent of past shows were one hour long, so one-hour shows were proposed as acceptable. They were leftovers from hosts calling in sick.'],
      ['A keyword match was too loose.', 'A note saying one person should get “as many operator shifts as possible” was read as the fill-every-hour flag, and that person was given 40 hours against a 30-hour limit.'],
      ['Two work sessions deployed over each other.', 'One pushed through CI while the other deployed directly. The repo is now push-only.'],
      ['Automatic reminders were never turned on.', 'Lark blocks messages across organisations from a personal account, and no SMS or email provider has been connected. The operations lead copies links by hand.'],
    ],
    openH: 'What still needs validation',
    open: [
      'How much of each draft survives review. Nobody has yet compared a generated draft with the schedule the client finally published.',
      'Net weekly time saved. The old first draft took about six hours. The current review and edit time has not been measured, so net hours saved are not claimed yet.',
      'Evening and weekend coverage, which depends on who signs up for those hours.',
      'Two operators in one room at the same hour, which the client’s hand-built schedule sometimes has.',
      'Scheduling two weeks ahead. The system only ever works on next week.',
    ],
    why: 'Why there is no net “hours saved” figure: the first full cycle ran in September 2026 and the client is still correcting rules every week. The number worth publishing is how many cells the operations lead changes before publishing, and that has not been counted yet.',
    teachH: 'What this case teaches about AI workflows',
    teach: [
      ['Historical data is not the same as business rules.', 'The one-hour shows in two months of schedules were sick-day leftovers. Ask the person who owns the process before encoding a pattern.'],
      ['Choose the correct unit of work.', 'People schedule in shows; the first version scheduled in hours. Changing the unit took mid-show operator changes from 41% to 0%.'],
      ['Keep client-owned rules outside the code.', 'Scores, pairings, hour ranges and room openings live in the client’s spreadsheet. A rule change is a cell edit.'],
      ['Explain why a request cannot be met.', 'An empty slot names the constraint that blocked it and how many people it blocked. That is how the last ten gaps were identified as a staffing problem.'],
      ['Automate the repeatable step; keep judgment where it belongs.', 'The first draft is generated. Review, edits, publishing and last-minute swaps stay with the operations lead.'],
      ['AI workflow design does not mean putting an LLM everywhere.', 'The client had already tried a chatbot. The part that had to be exact was written as code.'],
    ],
    outro: (ops, wf, tr) => `This is the same method taught in <a href="${tr}">corporate AI training</a>: pick one real task, write the rules down, and decide what a person must check. For more operations examples see <a href="${ops}">AI for Operations</a> and the <a href="${wf}">workflow library</a>.`,
  },
  zh: {
    name: '直播代运营公司的周排班',
    title: '案例：直播代运营公司的周排班 | AI Man Jack',
    description: '一家 TikTok Shop 直播代运营公司，以前每周从空白表格手排主播和运营。现在第一版班表自动生成，规则都在客户自己的表格里。',
    card: '以前每周排第一版班表大约要 6 小时。现在系统根据员工可播时间和客户自己维护的规则自动生成，最终仍由运营负责人审核、修改并发布。',
    tags: ['运营', '确定性排班', '人工审核'],
    eyebrow: '案例 · 运营',
    h1: '一家直播公司，不用再从空白表格开始排下周的班。',
    sub: '以前每周从零排出第一版班表大约要 6 小时。现在系统会根据员工可播时间、直播间要求和客户自己维护的规则自动生成第一版。最终班表仍由运营负责人审核、修改并发布。',
    trust: '2026 年 9 月上线 · 客户名称不公开 · 最终仍由人审核',
    summaryH: '一句话版本',
    summary: [
      '美国一家 TikTok Shop 直播代运营公司，约 30 名兼职主播和运营，8 个品牌直播间，每天大约 10 点到 21 点，一周七天。',
      '以前每周从零排出第一版班表大约要 6 小时，现在这一步已经自动生成。最终班表仍由运营负责人审核、修改并发布。',
      '排班的核心是确定性代码，没用 LLM。规则都在客户自己的表格里。',
      '排班单位从“小时”改成“场”之后，一场中途换运营的比例从 41% 降到 0%。最后一次实测排出 456 个角色小时，还有 10 个必排场次没排上，原因是晚间和周末报名的人不够。',
      '不写“净省多少小时”。现在审核和修改要花多久，还没有计时。',
    ],
    factsH: '基本情况',
    kv: [
      ['商家', 'TikTok Shop 直播代运营公司，美国（不公开名字）'],
      ['类型', '代运营品牌直播间，主播和运营都是兼职'],
      ['排班对象', '约 30 名兼职主播和运营，8 个品牌直播间，每天大约 10 点到 21 点，周末也开'],
      ['客户要的', '只要从 0 到 1 那一步：一版能用的下周班表草案'],
      ['不在系统里的', '考勤、工资、每日通知和最终发布，全部照旧'],
      ['状态', '已上线。每周出草案，运营负责人审核、修改、发布'],
    ],
    beforeH: '以前和现在',
    beforeP: '一位运营负责人每周挨个私聊要下周的可播时间，再在表格里一格一格填人。“只能到 4 点却排到了 5 点”这类冲突，靠排完以后肉眼找。',
    beforeK: '以前', before: ['每周大约 6 小时排第一版', '挨个问可播时间', '一格一格填班', '靠肉眼找冲突', '很多规则在负责人脑子里'],
    nowK: '现在', now: ['员工通过带签名的链接提交可播时间', '客户自己在 Lark 里维护规则', '确定性排班逻辑自动生成第一版', '没排上的场次会写明被哪条约束卡住', '运营负责人最后审核、修改、发布'],
    caveat: '以前每周从零排出第一版班表大约要 6 小时，现在这一步已经自动生成。最终班表仍由运营负责人审核、修改并发布。',
    builtH: '搭了什么',
    built: [
      '一个 Cloudflare Worker 加定时触发。每人一条带签名的链接，只对本周、只对本人有效，按天选开始和结束时间。提交记录进客户的 Lark 多维表格。',
      '每周四 Worker 读取可播时间、客户的打分表和直播间要求，把草案写回 Lark：每天一个页签，加一页汇总，再加一页用大白话写的排班逻辑。',
      '<strong>规则归客户。</strong>主播和直播间的匹配分、运营分、谁和谁不能同场、每周工时范围、哪个直播间几点开，全在客户的表格里。改规则是改单元格，不用找人改代码。',
      '<strong>系统不做的事：</strong>发布班表、给员工发消息、考勤、临时换班的判断。',
    ],
    llmH: '为什么用确定性代码，不用 LLM',
    llm: [
      '排班的核心是确定性代码，没用 LLM。',
      '做这个项目之前，客户试过把两个月的历史班表交给聊天机器人，让它照着往下排，结果规则没学会。第一次开会，运营负责人说模型“学得一坨”，老板的要求是“if A then B，不给它操作空间”。',
      '原因到后面才看清。历史班表里混着例外和残余，这些不是规则。过去的班表里有 5% 是一小时的场次，看着像规律，其实是主播临时请假留下的。只要是从历史里学，就会把残余和规则一起学进去。',
      '这条工作流要的是写明白的约束和可预期的兜底：搭档分是负数，就是永远不同场；周工时有上限，就是上限；排不上的场次，必须说明卡在哪条约束。LLM 在这类工作流的外围仍然有用，比如把主管随手写的一句备注整理成一条规则建议，再交给人确认。真正做排班决定的那部分，是确定性代码。',
    ],
    lesson: '需要处理模糊信息的地方用 LLM；业务规则必须一条不差执行的地方，用确定性逻辑。',
    notesH: '实现说明',
    notes: [
      '第一版按小时逐格找人，排出来的班没法上：一个人一天跑五个直播间，一场播到一半换运营。拿真实的一周对照才看出毛病在哪，人排班想的是“一场”，代码想的是“一小时”。后来排班单位改成 2 到 3 小时一场，每场一个主播配一个运营。',
      '先定运营，再配主播。这是客户的主管提的：下午两点有几个运营有空，决定了两点能开几个直播间。',
      '搭档分是负数的两个人，任何兜底阶段都不会排到一起。客户说得很清楚：能勉强一起播的，都没写负数。',
      '一场配不齐人时，先缩到两小时，再放宽到低一档的人，再允许别人来补剩下的一小时。还是不行就留空，汇总页写明卡在哪条约束、卡住了几个人。',
      '有一位主播是客户指定的例外：在这位主播唯一常播的直播间，把报上来的可播时间全部排满，不休息，不看上限。触发条件是客户表格里的一个标记，代码里没有写任何人的名字。',
      '每个日期页签第一行写着自己是星期几、几号。原因见下面“哪些地方坏过”。',
      '周三以后表格对员工关闭。运营负责人仍然可以打开任何人的链接，输入管理密码替对方提交。',
      '每次部署前跑 32 个自动测试，其中 10 个复现的是客户真实遇到过的 bug。',
    ],
    measureH: '测了什么',
    measureP1: '排班单位从“小时”改成“场”前后，生成结果和一份真实人工班表的结构对比：',
    t1: { head: ['', '人工排的一周', '按小时版', '按场次版'],
      rows: [['一小时的场次', '5%', '17%', '3%'], ['一场中途换运营', '26%', '41%', '0%'], ['单人单日最多跑几个直播间', '2', '5', '2'], ['单人单日最长工时', '7 小时', '8 小时', '7 小时']] },
    measureP2: '同一周里，规则逐条加进去之后的覆盖情况，以及还没排上的必排场次数。单位是角色小时：一个直播间开一小时算两份，主播一份，运营一份。',
    t2: { head: ['改动', '角色小时', '没排上的必排场次'],
      rows: [['改成按场次', '392', '25'], ['匹配分硬排序', '420', '20'], ['先定运营', '440', '18'], ['允许低一档的人顶班', '446', '16'], ['允许一小时补位', '456', '10']] },
    measureP3: '剩下的 10 个是晚上 7 点以后和周末的场次。汇总页给的原因是：二十多个人报的时间都够不到这些时段。这是人手问题，调排序解决不了。',
    failH: '真正上线前，哪些地方坏过',
    fails: [
      ['周五、周六、周日写进了错的页签。', '加了一个页签，之后每天整体错了一格。没有任何报错，错位后的结果看着还挺正常，因为周六和周日的班长得一样。是客户发现的：“周五很多人可以上班，但是都没排。”后来加了写入前的硬校验，再加上首行自报日期。'],
      ['有大半天所有人都提交不了。', '为了“同一个人本周只留一条记录”加的查询，用了 Lark 不接受的日期过滤写法。客户替别人提交时撞上的。'],
      ['从历史数据里推出了一条不存在的规则。', '过去的班表里 5% 是一小时的场次，于是提议允许一小时场次。其实那是主播临时请假留下的残余。'],
      ['关键词匹配写得太松。', '有人的备注写着“尽量多排运营”，被当成了“排满”的标记，结果排了 40 小时，而这个人的上限是 30。'],
      ['两个工作会话互相覆盖部署。', '一边走 CI 推送，一边本地直接部署，谁后跑谁生效。现在只允许走推送。'],
      ['自动催收一直没开。', 'Lark 不允许个人账号跨组织发消息，短信和邮件服务商也还没接。运营负责人现在手动复制链接发出去。'],
    ],
    openH: '还没验证的',
    open: [
      '每版草案有多少能原样留到发布。还没有人把生成的草案和客户最终发布的班表逐格比过。',
      '每周净省多少时间。以前第一版班表大约要 6 小时。现在审核和修改还要花多久没有正式计时，所以暂时不写“净省 6 小时”。',
      '晚间和周末的覆盖，取决于有没有人报这些时段。',
      '同一个直播间同一时段放两个运营，客户手排的班表里偶尔有。',
      '提前两周排班。系统现在只处理下周。',
    ],
    why: '为什么没有“净省了多少小时”：第一个完整周期是 2026 年 9 月才跑的，客户每周还在改规则。值得发的数字是运营负责人发布前改了多少格，这个还没数。',
    teachH: '这个案例说明了什么',
    teach: [
      ['历史数据不等于业务规则。', '两个月班表里的一小时场次是请假留下的，不是规则。把规律写进系统之前，先问流程的负责人。'],
      ['先选对工作单位。', '人排班想的是“一场”，第一版代码想的是“一小时”。单位一改，中途换运营的比例从 41% 降到 0%。'],
      ['客户的规则放在代码外面。', '匹配分、搭档、工时范围、直播间开播时间都在客户的表格里，改规则就是改单元格。'],
      ['做不到的时候，要说明原因。', '没排上的场次会写明卡在哪条约束、卡住了几个人。最后剩下的 10 个空缺，就是这样看出来是人手问题。'],
      ['重复的那一步自动化，需要判断的留给人。', '第一版自动生成；审核、修改、发布和临时换班，仍由运营负责人决定。'],
      ['设计 AI 工作流，不等于到处都放 LLM。', '客户已经试过聊天机器人。必须一条不差的那部分，最后写成了代码。'],
    ],
    outro: (ops, wf, tr) => `<a href="${tr}">企业 AI 培训</a>里教的就是这套方法：选一项真实任务，把规则写下来，再定好哪些地方必须由人核验。更多运营场景见<a href="${ops}">运营团队的 AI 应用</a>和<a href="${wf}">工作流库</a>。`,
  },
};

export const CURRENT_CASES = [LIVESTREAM];
