// llms.txt, generated by scripts/build.mjs from config.mjs so it cannot drift from the site's facts.
import { SITE, LEGAL_NAME, EMAIL, SMS_DISPLAY, PROOF, TRAINING, JACK_SAME_AS } from './config.mjs';

export const llms = () => `# AI Man Jack

> ${LEGAL_NAME} (aimanjack.com) is Jack Qian's Dallas, Texas company for corporate AI training and practical AI workflow training. Jack teaches non-technical teams — sales, operations, marketing, managers — in English or Chinese, onsite in Dallas–Fort Worth or remotely. Each participant brings a task they already do and leaves with a working AI workflow (ChatGPT, Claude, Gemini or Copilot) plus a checklist for verifying its output. Formats: a 90-minute session, a half-day hands-on workshop (from $${TRAINING.halfDayFrom.toLocaleString()} for up to ${TRAINING.halfDayMax} people) and a multi-week program. Evidence shown on the site: ${PROOF.talks} community AI talks in Plano and Dallas with ${PROOF.perTalk} people each, one ${PROOF.hackathon}-person AI hackathon, and ${PROOF.reviews} Google reviews averaging ${PROOF.rating}. To plan a team workshop, book a 30-minute call at ${SITE}/book/, email ${EMAIL}, or text TRAINING to ${SMS_DISPLAY}.

Key facts:
- Company: ${LEGAL_NAME}, Dallas, Texas. Founder and trainer: Jack Qian. One person designs, teaches and follows up.
- Service: corporate AI training and AI workflow training for teams of roughly 5 to 60 people. Taught in English or Chinese. Onsite anywhere in Dallas–Fort Worth (Dallas, Fort Worth, Plano, Richardson, Frisco, McKinney, Arlington); remote on request.
- Method, five parts: choose a suitable task, give the AI useful context, move from chat to workflow, verify the output, apply data and approval guardrails. Two weeks after a session Jack checks whether the workflow was tested, was accurate enough to use, and should continue, change or stop.
- Tools: whichever the company has approved — ChatGPT, Claude, Gemini, Microsoft Copilot. The method is tool-agnostic. No coding.
- Pricing: half-day hands-on workshops from $${TRAINING.halfDayFrom.toLocaleString()} for up to ${TRAINING.halfDayMax} people at the client's office. 90-minute sessions and multi-week programs are quoted by team size after one 30-minute call; written quote within 24 hours.
- Proof: ${PROOF.talks} community talks (${PROOF.perTalk} attendees each), one ${PROOF.hackathon}-person hackathon, ${PROOF.reviews} Google reviews at ${PROOF.rating}, all from workshop attendees. No client ROI figures are claimed.
- Sister site: https://realagentusecases.com/ — Jack's weekly newsletter on AI agents and workflows working professionals actually run (learn there; train with AI Man Jack).
- Profiles: ${JACK_SAME_AS.filter((u) => !/facebook|nextdoor|luma/.test(u)).join(' · ')}

## Pages

- [Home](${SITE}/): who AI Man Jack trains, what a team can do after training, formats, proof, FAQ
- [Corporate AI training](${SITE}/ai-training/): the five-part curriculum, who it is for, formats and pricing, Google reviews, FAQ
- [Resources](${SITE}/blog/): field notes on training employees to use AI and on AI workflows
- [About](${SITE}/about/): Jack Qian and ${LEGAL_NAME}
- [Book a 30-minute call](${SITE}/book/): choose a US Central time to plan a team workshop
- [Contact](${SITE}/contact/): book, email or text

Chinese versions of every page live under ${SITE}/zh/ (for example ${SITE}/zh/ai-training/).

## Optional

- [Terms of Service](${SITE}/terms)
- [Privacy policy](${SITE}/privacy)
- [SMS terms](${SITE}/sms-terms)
`;
