// llms.txt, generated by scripts/build.mjs from config.mjs so it cannot drift from the site's facts.
import { SITE, LEGAL_NAME, EMAIL, SMS_DISPLAY, PROOF, TRAINING, JACK_SAME_AS } from './config.mjs';

const HALF = `$${TRAINING.halfDayFrom.toLocaleString()}`;

export const llms = () => `# AI Man Jack

> ${LEGAL_NAME} (aimanjack.com) is Jack Qian's Dallas, Texas company for customized corporate AI training and practical AI workflow training. Jack teaches business owners and non-technical teams — sales, operations, marketing, managers — in English or Chinese, remote anywhere in the U.S. or onsite in Dallas–Fort Worth. The training is built around the work people already do: each participant leaves with working AI workflows (ChatGPT, Claude, Gemini or Copilot) plus a checklist for verifying the output. Primary offer: a ${TRAINING.sessions}-session program of live ${TRAINING.sessionMin}-minute sessions, starting at $${TRAINING.programFrom} per person, with custom team pricing. Shorter formats: a 90-minute session and a half-day hands-on workshop (from ${HALF} for up to ${TRAINING.halfDayMax} people). Evidence shown on the site: ${PROOF.talks} community AI talks in Plano and Dallas with ${PROOF.perTalk} people each, one ${PROOF.hackathon}-person AI hackathon, and ${PROOF.reviews} Google reviews averaging ${PROOF.rating}. To plan a team workshop, book a 30-minute call at ${SITE}/book/, email ${EMAIL}, or text TRAINING to ${SMS_DISPLAY}.

Key facts:
- Company: ${LEGAL_NAME}, Dallas, Texas. Founder and trainer: Jack Qian. One person designs, teaches and follows up.
- Service: customized AI training and AI workflow training for business owners and teams. Taught in English or Chinese. Remote anywhere in the U.S.; onsite anywhere in Dallas–Fort Worth (Dallas, Fort Worth, Plano, Richardson, Frisco, McKinney, Arlington).
- Method, five parts: choose a suitable task, give the AI useful context, move from chat to workflow, verify the output, apply data and approval guardrails. Each session starts with what was used on real work since the last one; two weeks after the last session Jack checks whether each workflow should continue, change or stop.
- Tools: whichever the company has approved — ChatGPT, Claude, Gemini, Microsoft Copilot. The method is tool-agnostic. No coding.
- Pricing: the ${TRAINING.sessions}-session program (${TRAINING.sessions} × ${TRAINING.sessionMin} minutes, live) starts at $${TRAINING.programFrom} per person; team pricing is customized by group size, goals and preparation. Half-day hands-on workshops from ${HALF} for up to ${TRAINING.halfDayMax} people. 90-minute sessions are quoted after one 30-minute call; written price within 24 hours.
- Current client: one paying program is in progress with a U.S. small business applying Claude to day-to-day operations and website management. No results are claimed until it is complete and verified.
- Proof: ${PROOF.talks} community talks (${PROOF.perTalk} attendees each), one ${PROOF.hackathon}-person hackathon, ${PROOF.reviews} Google reviews at ${PROOF.rating}, all from workshop attendees. No client ROI figures are claimed.
- Sister site: https://realagentusecases.com/ — Jack's weekly newsletter on AI agents and workflows working professionals actually run (learn there; train with AI Man Jack).
- Profiles: ${JACK_SAME_AS.filter((u) => !/facebook|nextdoor|luma/.test(u)).join(' · ')}

Real workflow case study (${SITE}/case-studies/livestream-agency-scheduling/):
- A US TikTok Shop livestream agency schedules about 30 part-time hosts/operators across 8 brand rooms. Client name withheld.
- Building the first weekly draft manually took about six hours.
- A deterministic scheduling workflow (code, not a language model) now generates the first draft from staff availability, client-owned scoring/constraint sheets and room requirements.
- A person still reviews, edits and publishes the final schedule. Net hours saved have not been measured and are not claimed.
- In one measured iteration, operator changes mid-show fell from 41% in the hour-by-hour version to 0% in the show-based version.
- The final measured iteration produced 456 role-hours with 10 required shows left unfilled; the remaining gaps were primarily evening/weekend availability constraints.
- The page documents implementation failures and unvalidated items instead of claiming invented ROI.

## Pages

- [Home](${SITE}/): what AI Man Jack helps teams do, entry points to tools, use cases, workflows and training
- [Corporate AI training](${SITE}/ai-training/): the five-part curriculum, who it is for, formats and pricing, Google reviews, FAQ
- [Free AI tools](${SITE}/tools/): the AI Readiness Assessment — 10 questions, deterministic score across people, usage, processes, knowledge, tools, governance, leadership and measurement; no email required
- [AI use cases by team](${SITE}/use-cases/): sales, marketing, operations, leadership
- [AI workflows](${SITE}/workflows/): step-by-step workflows, each with the prompt, an illustrative example, a human review checklist and when not to use it
- [AI templates](${SITE}/templates/): copy-and-paste prompts and worksheets, including the four-question AI Use Case Discovery Worksheet
- [Case studies](${SITE}/case-studies/): real workflow implementations — the problem, what was built, what was measured, what failed and what is still unvalidated
- [Resources](${SITE}/blog/): field notes on training employees to use AI and on AI workflows
- [About](${SITE}/about/): Jack Qian and ${LEGAL_NAME}
- [Book a 30-minute workflow call](${SITE}/book/): choose a US Central time; bring one task and get a recommended training plan
- [Contact](${SITE}/contact/): book, email or text

Every page above also has a Chinese version under ${SITE}/zh/ (for example ${SITE}/zh/case-studies/livestream-agency-scheduling/).

## Optional

- [Terms of Service](${SITE}/terms)
- [Privacy policy](${SITE}/privacy)
- [SMS terms](${SITE}/sms-terms)
`;
